name: Build
on:
  push:
    branches: ["**", "!main"]
permissions:
  contents: read
  packages: write
  security-events: write
jobs:
  build:
    uses: batinicaz/gha/.github/workflows/docker.yml@04fd71588f6e19a10ea68d1beb5e6faabab7487d # ratchet:batinicaz/gha/.github/workflows/docker.yml@v1.5.3
    with:
      runner: ubuntu-24.04-arm
      push: false
    secrets:
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
