name: Build
on:
  push:
    branches: ["**", "!main"]
permissions:
  contents: read
  packages: write
  security-events: write
jobs:
  build:
    uses: batinicaz/gha/.github/workflows/docker.yml@24fd80622a741a0490b9641b194c63d9a1a5cd7a # ratchet:batinicaz/gha/.github/workflows/docker.yml@v1.5.3
    with:
      runner: ubuntu-24.04-arm
      push: false
    secrets:
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
