name: Release
on:
  push:
    branches: ["main"]
permissions:
  contents: write
jobs:
  release:
    uses: batinicaz/gha/.github/workflows/release.yml@a58beae491a37827648811ec6c5ee14a30cafe36 # ratchet:batinicaz/gha/.github/workflows/release.yml@v1.7.4
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
