name: Build & Publish
on:
  push:
    tags: ["v*"]
permissions:
  contents: read
  packages: write
  security-events: write
jobs:
  publish:
    uses: batinicaz/gha/.github/workflows/docker.yml@26cc6de635db027946310b51915b0106a56d2635 # ratchet:batinicaz/gha/.github/workflows/docker.yml@v1.5.2
    with:
      runner: ubuntu-24.04-arm
    secrets:
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
